// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwQRqnV-arpadoVz7x9rgn88i3_A-kh-0',
    appId: '1:194931270842:android:a35fffbf3ec2242bc98e83',
    messagingSenderId: '194931270842',
    projectId: 'eveiloo-flutter',
    storageBucket: 'eveiloo-flutter.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEckM_HqfvhxPzKfTkPqF4tNh7KdflBzU',
    appId: '1:194931270842:web:ec73cf84204d2bf1c98e83',
    messagingSenderId: '194931270842',
    projectId: 'eveiloo-flutter',
    authDomain: 'eveiloo-flutter.firebaseapp.com',
    storageBucket: 'eveiloo-flutter.firebasestorage.app',
    measurementId: 'G-946LLZF0CX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvPp4rUudAtxyNIv_GPhIuHYoMZkeDdz8',
    appId: '1:194931270842:ios:51af81a491db3dc4c98e83',
    messagingSenderId: '194931270842',
    projectId: 'eveiloo-flutter',
    storageBucket: 'eveiloo-flutter.firebasestorage.app',
    iosBundleId: 'com.example.eveilooEnfant',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvPp4rUudAtxyNIv_GPhIuHYoMZkeDdz8',
    appId: '1:194931270842:ios:51af81a491db3dc4c98e83',
    messagingSenderId: '194931270842',
    projectId: 'eveiloo-flutter',
    storageBucket: 'eveiloo-flutter.firebasestorage.app',
    iosBundleId: 'com.example.eveilooEnfant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEckM_HqfvhxPzKfTkPqF4tNh7KdflBzU',
    appId: '1:194931270842:web:011a7aaee859e77ac98e83',
    messagingSenderId: '194931270842',
    projectId: 'eveiloo-flutter',
    authDomain: 'eveiloo-flutter.firebaseapp.com',
    storageBucket: 'eveiloo-flutter.firebasestorage.app',
    measurementId: 'G-1FTLKX02VZ',
  );
}
